[package]
name = "transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
protocol-core = { workspace = true, features = ["alloc"] }
bytes.workspace = true
futures-util = { workspace = true, features = ["sink"] }
tokio = { workspace = true, features = ["net", "time", "io-util", "rt", "sync"] }
tokio-util = { workspace = true, features = ["codec"] }
thiserror.workspace = true
getrandom.workspace = true
rand_core.workspace = true
rand_chacha.workspace = true
